"""empty message

Revision ID: 24961c3aa774
Revises: 4c763d9cffd4
Create Date: 2024-12-15 06:57:12.532974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24961c3aa774'
down_revision = '4c763d9cffd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_schedule',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_name', sa.String(length=50), nullable=False),
    sa.Column('schedule_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_code')
    )
    op.create_index(op.f('ix_user_schedule_id'), 'user_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_user_schedule_user_id'), 'user_schedule', ['user_id'], unique=False)
    op.add_column('user_event_type', sa.Column('schedule_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_user_event_type_schedule_id'), 'user_event_type', ['schedule_id'], unique=False)
    op.add_column('user_recurring_slot', sa.Column('schedule_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_user_recurring_slot_schedule_id'), 'user_recurring_slot', ['schedule_id'], unique=False)
    op.add_column('user_slot', sa.Column('booked_by_user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('user_slot', sa.Column('user_event_type_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_user_slot_booked_by_user_id'), 'user_slot', ['booked_by_user_id'], unique=False)
    op.create_index(op.f('ix_user_slot_user_event_type_id'), 'user_slot', ['user_event_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_slot_user_event_type_id'), table_name='user_slot')
    op.drop_index(op.f('ix_user_slot_booked_by_user_id'), table_name='user_slot')
    op.drop_column('user_slot', 'user_event_type_id')
    op.drop_column('user_slot', 'booked_by_user_id')
    op.drop_index(op.f('ix_user_recurring_slot_schedule_id'), table_name='user_recurring_slot')
    op.drop_column('user_recurring_slot', 'schedule_id')
    op.drop_index(op.f('ix_user_event_type_schedule_id'), table_name='user_event_type')
    op.drop_column('user_event_type', 'schedule_id')
    op.drop_index(op.f('ix_user_schedule_user_id'), table_name='user_schedule')
    op.drop_index(op.f('ix_user_schedule_id'), table_name='user_schedule')
    op.drop_table('user_schedule')
    # ### end Alembic commands ###
