"""empty message

Revision ID: ba5c74ad9345
Revises: 24961c3aa774
Create Date: 2024-12-15 07:00:27.507993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5c74ad9345'
down_revision = '24961c3aa774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_event_type_user_id_code', 'user_event_type', ['user_id', 'code'], unique=True)
    op.create_index('ix_user_schedule_user_id_code', 'user_schedule', ['user_id', 'schedule_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_schedule_user_id_code', table_name='user_schedule')
    op.drop_index('ix_user_event_type_user_id_code', table_name='user_event_type')
    # ### end Alembic commands ###
